version: "3"

networks:
  cmos:

services:
  cmos-core:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - cmos

  pgsql:
    image: postgres:10.19-alpine3.14
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgsql:/var/lib/pgsql  #Folder konfig backup
    networks:
      - cmos
    env_file:
      - database.env # Database konfigurasi

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cmos
